### ISSUE TITLE
xor's mask can't be hexadecimal ('0x' isn't recognized and -x argument isn't valid)

### ISSUE THREAD

**Issue by q2dg** [dirtbags/fluffy#4]
I've downloaded xor.c from your repository and I've compiled simply by doing: _gcc -o xor.exe xor.c_  (where gcc's version is gcc  10.2.1 20201125 (Red Hat 10.2.1-9) and my system is Fedora 33). From here, a picture is worth a thousand words: 

![Captura de pantalla de 2021-02-03 01-12-39](https://user-images.githubusercontent.com/7274874/106679486-14f8b500-65bd-11eb-8a73-a7ac82ef190b.png)

Thanks a lot

**Comment by nealey** [comment]
Oops.

**Comment by nealey** [comment]
Thanks for the bug report! I'm going to go write a regression test harness now :)
